In [1]:
from pathlib import Path
import sys

import pandas as pd

project_root = Path.cwd()
if not (project_root / "src").exists():
    project_root = project_root.parent

if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))
  
from src.graph import *

In [2]:
df = load_calendar_data()
df.head()

,service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
0,1000_398129,1,1,1,1,1,1,1,2026-02-25,2026-03-07
1,1001_398130,1,1,1,1,1,1,1,2026-03-08,2026-05-27
2,1002_398131,1,1,1,1,1,1,1,2026-05-28,2026-06-13
3,1003_398132,1,1,1,1,1,1,1,2026-06-14,2026-12-12
4,100_397108,1,1,1,1,1,1,1,2026-06-06,2026-06-06

In [3]:
test_date = pd.Timestamp("2026-03-10")
filtered_df = filter_calendar_by_date(df, test_date)
filtered_df[["service_id", "tuesday", "start_date", "end_date"]].head()

     service_id  tuesday start_date   end_date
1   1001_398130        1 2026-03-08 2026-05-27
6   1005_398134        1 2026-03-08 2026-06-13
8   1007_398136        1 2026-03-08 2026-06-13
10  1009_398138        1 2026-03-09 2026-06-12
17  1015_398144        1 2026-03-09 2026-06-12

In [4]:
day_services = get_day_services(filtered_df)
len(day_services)

745

In [5]:
data_exceptions_df = load_calendar_exceptions_data()
data_exceptions_df.head()

    service_id       date  exception_type
0  2808_400204 2026-03-09               2
1    33_397029 2026-03-09               1
2    36_397033 2026-03-09               1
3    45_397043 2026-03-09               1
4    48_397047 2026-03-09               1

In [6]:
filtered_exceptions = filter_calendar_exceptions_by_date(data_exceptions_df,  test_date)
filtered_exceptions.head()

     service_id       date  exception_type
17  2580_399958 2026-03-10               2
18  2589_399969 2026-03-10               2
19  2598_399978 2026-03-10               2
20  2708_400101 2026-03-10               2
21  2808_400204 2026-03-10               2

In [7]:
active_services = get_active_services_for_date(day_services, filtered_exceptions)
len(active_services)

756

In [8]:
trips_df = load_trips_data()
print(str(len(trips_df)))
trips_df.head()

3263

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id
0,234088,1_396994,37148498_396994,Sędzisław,NaN,25400/60461
1,234088,2_396995,37148499_396995,Sędzisław,NaN,25400/60461
2,234088,3_396996,37148500_396996,Sędzisław,NaN,25400/60461
3,234088,4_396997,37148501_396997,Sędzisław,NaN,25402/60463
4,234088,5_396998,37148502_396998,Sędzisław,NaN,25402/60463

In [9]:
filtered_trips_df = filter_trips_by_service_id(trips_df, active_services)
print(str(len(filtered_trips_df)))
filtered_trips_df.head()

756

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id
1,234088,2_396995,37148499_396995,Sędzisław,NaN,25400/60461
3,234088,4_396997,37148501_396997,Sędzisław,NaN,25402/60463
12,234088,13_397007,37148511_397007,Sędzisław,NaN,25408/60467
15,234088,16_397010,37148514_397010,Sędzisław,NaN,25410/60469
17,234088,18_397012,37148516_397012,Sędzisław,NaN,25412/60471

In [10]:
stop_times_df = load_stop_times_data()
print(str(len(stop_times_df)))
stop_times_df.head()

48748

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,shape_dist_traveled
0,37148498_396994,05:36:00,05:36:00,1474824,0,NaN,0,NaN
1,37148498_396994,05:41:00,05:41:00,1474825,1,NaN,0,NaN
2,37148498_396994,05:48:00,05:48:00,1474826,2,NaN,0,NaN
3,37148498_396994,05:55:00,05:55:00,1474827,3,NaN,0,NaN
4,37148498_396994,05:58:00,05:58:00,1474828,4,NaN,0,NaN

In [11]:
filtered_stop_times = filter_stop_times_by_trip_id(stop_times_df, filtered_trips_df)
print(str(len(filtered_stop_times)))
filtered_stop_times.head()
# filtered_stop_times[filtered_stop_times["trip_id"] == "37148747_397243"]

9947

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,shape_dist_traveled
10,37148499_396995,06:07:00,06:07:00,1474829,0,NaN,0,NaN
11,37148499_396995,06:12:00,06:13:00,1474830,1,NaN,0,NaN
12,37148499_396995,06:18:00,06:19:00,1474831,2,NaN,0,NaN
13,37148499_396995,06:25:00,06:25:00,1474832,3,NaN,0,NaN
14,37148499_396995,06:34:00,06:34:00,1474758,4,NaN,1,NaN

In [12]:
trips_dict = get_stop_times_dict_by_trip_id(filtered_stop_times, filtered_trips_df)
print(trips_dict.keys())
trips_dict['37148747_397243']

dict_keys(['37148499_396995', '37148501_396997', '37148511_397007', '37148514_397010', '37148516_397012', '37148519_397015', '37148524_397020', '37148526_397022', '37148530_397026', '37148533_397029', '37148537_397033', '37148540_397036', '37148544_397040', '37148547_397043', '37148551_397047', '37148554_397050', '37148558_397054', '37148561_397057', '37148565_397061', '37148568_397064', '37148572_397068', '37148575_397071', '37148579_397075', '37148582_397078', '37148586_397082', '37148589_397085', '37148593_397089', '37148596_397092', '37148600_397096', '37148603_397099', '37148607_397103', '37148619_397115', '37148622_397118', '37148625_397121', '37148628_397124', '37148631_397127', '37148634_397130', '37148637_397133', '37148640_397136', '37148656_397152', '37148659_397155', '37148664_397160', '37148669_397165', '37148674_397170', '37148684_397180', '37148690_397186', '37148695_397191', '37148700_397196', '37148704_397200', '37148709_397205', '37148714_397210', '37148717_397213', '37148724_397220', '37148729_397225', '37148733_397229', '37148739_397235', '37148744_397240', '37148747_397243', '37148752_397248', '37148757_397253', '37148760_397256', '37148766_397262', '37148771_397267', '37148780_397276', '37148786_397282', '37148792_397288', '37148800_397296', '37148806_397302', '37148809_397305', '37148814_397310', '37148818_397314', '37148822_397318', '37148830_397326', '37148837_397333', '37148841_397337', '37148847_397343', '37148850_397346', '37148853_397349', '37148857_397353', '37148863_397359', '37148866_397362', '37148869_397365', '37148872_397368', '37148882_397378', '37148886_397382', '37148890_397386', '37148897_397393', '37148900_397396', '37148903_397399', '37148912_397408', '37148915_397411', '37148921_397417', '37148925_397421', '37148931_397427', '37148934_397430', '37148937_397433', '37148943_397439', '37148946_397442', '37148950_397446', '37148952_397448', '37148955_397451', '37148960_397456', '37148963_397459', '37148966_397462', '37148973_397469', '37148981_397477', '37148984_397480', '37148986_397482', '37148989_397485', '37148992_397488', '37148996_397492', '37149002_397498', '37149009_397505', '37149012_397508', '37149015_397511', '37149021_397517', '37149024_397520', '37149027_397523', '37149029_397525', '37149036_397532', '37149039_397535', '37149042_397538', '37149046_397542', '37149052_397548', '37149057_397553', '37149060_397556', '37149063_397559', '37149066_397562', '37149071_397567', '37149074_397570', '37149081_397577', '37149084_397580', '37149087_397583', '37149095_397591', '37149098_397594', '37149102_397598', '37149108_397604', '37149112_397608', '37149115_397611', '37149118_397614', '37149121_397617', '37149124_397620', '37149127_397623', '37149132_397628', '37149138_397634', '37149142_397638', '37149145_397641', '37149148_397644', '37149151_397647', '37149154_397650', '37149157_397653', '37149173_397669', '37149183_397679', '37149191_397687', '37149200_397696', '37149205_397701', '37149215_397711', '37149219_397715', '37149231_397727', '37149259_397755', '37149265_397761', '37149268_397764', '37149270_397766', '37149273_397769', '37149276_397772', '37149279_397775', '37149285_397781', '37149289_397785', '37149292_397788', '37149295_397791', '37149299_397795', '37149302_397798', '37149308_397804', '37149312_397808', '37149321_397817', '37149325_397821', '37149330_397826', '37149335_397831', '37149345_397841', '37149352_397848', '37149359_397855', '37149369_397865', '37149377_397873', '37149381_397877', '37149384_397880', '37149389_397885', '37149391_397887', '37149393_397889', '37149396_397892', '37149399_397895', '37149404_397900', '37149410_397906', '37149416_397912', '37149421_397917', '37149423_397919', '37149429_397925', '37149435_397931', '37149444_397940', '37149449_397945', '37149460_397956', '37149464_397960', '37149469_397965', '37149473_397969', '37149476_397972', '37149480_397976', '37149484_397980', '37149489_397985', '37149499_397995', '37149512_398008', '37149519_398015', '37149523_398019', '37149538_398034', '37149542_398038', '37149545_398041', '37149550_398046', '37149554_398050', '37149562_398058', '37149566_398062', '37149591_398087', '37149597_398093', '37149606_398102', '37149610_398106', '37149613_398109', '37149618_398114', '37149619_398115', '37149622_398118', '37149624_398120', '37149625_398121', '37149628_398124', '37149632_398128', '37149634_398130', '37149638_398134', '37149640_398136', '37149642_398138', '37149648_398144', '37149650_398146', '37149652_398148', '37149654_398150', '37149674_398170', '37149676_398172', '37149679_398175', '37149681_398177', '37149684_398180', '37149686_398182', '37149689_398185', '37149692_398188', '37149695_398191', '37149697_398193', '37149700_398196', '37149702_398198', '37149704_398200', '37149707_398203', '37149710_398206', '37149713_398209', '37149716_398212', '37149719_398215', '37149722_398218', '37149724_398220', '37149725_398221', '37149727_398223', '37149728_398224', '37149729_398225', '37149730_398226', '37149731_398227', '37149732_398228', '37149733_398229', '37149734_398230', '37149735_398231', '37149736_398232', '37149737_398233', '37149738_398234', '37149739_398235', '37149740_398236', '37149741_398237', '37149742_398238', '37149743_398239', '37149744_398240', '37149745_398241', '37149746_398242', '37149747_398243', '37149748_398244', '37149749_398245', '37149750_398246', '37149751_398247', '37149755_398251', '37149759_398255', '37149762_398258', '37149767_398263', '37149775_398271', '37149779_398275', '37149782_398278', '37149786_398282', '37149795_398291', '37149803_398299', '37149806_398302', '37149809_398305', '37149813_398309', '37149817_398313', '37149820_398316', '37149828_398324', '37149834_398330', '37149845_398341', '37149852_398348', '37149860_398356', '37149865_398361', '37149870_398366', '37149874_398370', '37149877_398373', '37149880_398376', '37149883_398379', '37149887_398383', '37149893_398389', '37149897_398393', '37149902_398398', '37149905_398401', '37149908_398404', '37149911_398407', '37149915_398411', '37149922_398418', '37149928_398424', '37149932_398428', '37149935_398431', '37149941_398437', '37149944_398440', '37149947_398443', '37149950_398446', '37149953_398449', '37149958_398454', '37149961_398457', '37149964_398460', '37149967_398463', '37149973_398469', '37149976_398472', '37149979_398475', '37149982_398478', '37149985_398481', '37149988_398484', '37149992_398488', '37149998_398494', '37150005_398501', '37150007_398503', '37150010_398506', '37150013_398509', '37150016_398512', '37150019_398515', '37150022_398518', '37150024_398520', '37150026_398522', '37150028_398524', '37150030_398526', '37150032_398528', '37150035_398531', '37150038_398534', '37150040_398536', '37150043_398539', '37150045_398541', '37150048_398544', '37150052_398548', '37150055_398551', '37150058_398554', '37150060_398556', '37150063_398559', '37150066_398562', '37150069_398565', '37150072_398568', '37150075_398571', '37150078_398574', '37150083_398579', '37150086_398582', '37150088_398584', '37150094_398590', '37150097_398593', '37150099_398595', '37150102_398598', '37150105_398601', '37150108_398604', '37150111_398607', '37150118_398614', '37150121_398617', '37150122_398618', '37150125_398621', '37150127_398623', '37150130_398626', '37150138_398634', '37150141_398637', '37150145_398641', '37150150_398646', '37150153_398649', '37150154_398650', '37150157_398653', '37150160_398656', '37150162_398658', '37150173_398669', '37150176_398672', '37150187_398683', '37150190_398686', '37150197_398693', '37150201_398697', '37150209_398705', '37150212_398708', '37150218_398714', '37150222_398718', '37150225_398721', '37150231_398727', '37150238_398734', '37150242_398738', '37150246_398742', '37150257_398753', '37150262_398758', '37150272_398768', '37150281_398777', '37150289_398785', '37150296_398792', '37150305_398801', '37150309_398805', '37150314_398810', '37150320_398816', '37150328_398824', '37150335_398831', '37150341_398837', '37150378_398874', '37150388_398884', '37150392_398888', '37150406_398902', '37150412_398908', '37150426_398922', '37150440_398936', '37150446_398942', '37150456_398952', '37150465_398961', '37150469_398965', '37150473_398969', '37150478_398974', '37150484_398980', '37150488_398984', '37150491_398987', '37150497_398993', '37150502_398998', '37150509_399005', '37150513_399009', '37150521_399017', '37150527_399023', '37150533_399029', '37150538_399034', '37150544_399040', '37150550_399046', '37150557_399053', '37150564_399060', '37150571_399067', '37150583_399079', '37150595_399091', '37150601_399097', '37150604_399100', '37150614_399110', '37150628_399124', '37150641_399137', '37150647_399143', '37150653_399149', '37150657_399153', '37150663_399159', '37150675_399171', '37150683_399179', '37150686_399182', '37150691_399187', '37150696_399192', '37150701_399197', '37150704_399200', '37150711_399207', '37150723_399219', '37150738_399234', '37150749_399245', '37150766_399262', '37150783_399279', '37150790_399286', '37150796_399292', '37150800_399296', '37150807_399303', '37150814_399310', '37150820_399316', '37150825_399321', '37150839_399335', '37150843_399339', '37150849_399345', '37150852_399348', '37150855_399351', '37150858_399354', '37150862_399358', '37150865_399361', '37150870_399366', '37150874_399370', '37150877_399373', '37150880_399376', '37150883_399379', '37150887_399383', '37150890_399386', '37150893_399389', '37150896_399392', '37150899_399395', '37150902_399398', '37150904_399400', '37150905_399401', '37150906_399402', '37150907_399403', '37150908_399404', '37150909_399405', '37150911_399407', '37150914_399410', '37150917_399413', '37150921_399417', '37150924_399420', '37150929_399425', '37150933_399429', '37150936_399432', '37150940_399436', '37150943_399439', '37150947_399443', '37150950_399446', '37150953_399449', '37150956_399452', '37150959_399455', '37150962_399458', '37150966_399462', '37150967_399463', '37150968_399464', '37150969_399465', '37150970_399466', '37150971_399467', '37150974_399470', '37150981_399477', '37150989_399485', '37150997_399493', '37151001_399497', '37151011_399507', '37151018_399514', '37151032_399528', '37151043_399539', '37151052_399548', '37151060_399556', '37151066_399562', '37151070_399566', '37151080_399576', '37151085_399581', '37151090_399586', '37151098_399594', '37151103_399599', '37151109_399605', '37151114_399610', '37151122_399618', '37151130_399626', '37151133_399629', '37151139_399635', '37151145_399641', '37151148_399644', '37151151_399647', '37151154_399650', '37151157_399653', '37151160_399656', '37151163_399659', '37151168_399664', '37151172_399668', '37151175_399671', '37151178_399674', '37151181_399677', '37151184_399680', '37151191_399687', '37151195_399691', '37151198_399694', '37151201_399697', '37151204_399700', '37151207_399703', '37151210_399706', '37151215_399711', '37151219_399715', '37151223_399719', '37151226_399722', '37151229_399725', '37151232_399728', '37151235_399731', '37151241_399737', '37151245_399741', '37151249_399745', '37151254_399750', '37151258_399754', '37151261_399757', '37151264_399760', '37151268_399764', '37151271_399767', '37151274_399770', '37151278_399774', '37151283_399779', '37151288_399784', '37151294_399790', '37151298_399794', '37151300_399796', '37151303_399799', '37151312_399808', '37151317_399813', '37151320_399816', '37151325_399821', '37151336_399832', '37151339_399835', '37151347_399843', '37151354_399850', '37151362_399858', '37151367_399863', '37151375_399871', '37151388_399884', '37151406_399902', '37151411_399907', '37151415_399911', '37151419_399915', '37151430_399926', '37151463_399959', '37151474_399970', '37151483_399979', '37151487_399983', '37151496_399992', '37151504_400000', '37151508_400004', '37151516_400012', '37151527_400023', '37151533_400029', '37151539_400035', '37151543_400039', '37151547_400043', '37151551_400047', '37151559_400055', '37151564_400060', '37151570_400066', '37151576_400072', '37151584_400080', '37151589_400085', '37151606_400102', '37151610_400106', '37151619_400115', '37151623_400119', '37151627_400123', '37151631_400127', '37151637_400133', '37151643_400139', '37151649_400145', '37151655_400151', '37151659_400155', '37151663_400159', '37151667_400163', '37151671_400167', '37151675_400171', '37151680_400176', '37151685_400181', '37151690_400186', '37151696_400192', '37151702_400198', '37151709_400205', '37151719_400215', '37151733_400229', '37151735_400231', '37151738_400234', '37151741_400237', '37151744_400240', '37151752_400248', '37151755_400251', '37151760_400256', '37151763_400259', '37151766_400262', '37151769_400265', '37151774_400270', '37151777_400273', '37151779_400275', '37151788_400284', '37151792_400288', '37151800_400296', '37151803_400299', '37151814_400310', '37151819_400315', '37151822_400318', '37151828_400324', '37151831_400327', '37151834_400330', '37151842_400338', '37151844_400340', '37151848_400344', '37151850_400346', '37151861_400357', '37151866_400362', '37151870_400366', '37151874_400370', '37151878_400374', '37151882_400378', '37151886_400382', '37151891_400387', '37151895_400391', '37151899_400395', '37151904_400400', '37151910_400406', '37151915_400411', '37151919_400415', '37151924_400420', '37151928_400424', '37151932_400428', '37151940_400436', '37151944_400440', '37151954_400450', '37151958_400454', '37151962_400458', '37151966_400462', '37151970_400466', '37151975_400471', '37151979_400475', '37151983_400479', '37151987_400483', '37151990_400486', '37151993_400489', '37152008_400504', '37152011_400507', '37152020_400516', '37152024_400520', '37152031_400527', '37152037_400533', '37152043_400539', '37152047_400543', '37152057_400553', '37152062_400558', '37152067_400563', '37152075_400571', '37152081_400577', '37152086_400582', '37152091_400587', '37152099_400595', '37152104_400600', '37152110_400606', '37152120_400616', '37152127_400623', '37152134_400630', '37152141_400637', '37152145_400641', '37152153_400649', '37152162_400658', '37152172_400668', '37152178_400674', '37152181_400677', '37152187_400683', '37152190_400686', '37152193_400689', '37152196_400692', '37152199_400695', '37152202_400698', '37152205_400701', '37152208_400704', '37152211_400707', '37152214_400710', '37152217_400713', '37152220_400716', '37152222_400718', '37152224_400720', '37152226_400722', '37152228_400724'])

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,shape_dist_traveled
0,37148747_397243,11:39:00,11:39:00,1474617,0,NaN,0,NaN
1,37148747_397243,11:43:00,11:44:00,1609725,1,NaN,0,NaN
2,37148747_397243,11:50:00,11:50:00,1474944,2,NaN,0,NaN
3,37148747_397243,11:54:00,11:54:00,2414688,3,NaN,0,NaN
4,37148747_397243,12:00:00,12:01:00,1474942,4,NaN,0,NaN
5,37148747_397243,12:05:00,12:06:00,1474941,5,NaN,0,NaN
6,37148747_397243,12:12:00,12:13:00,1474940,6,NaN,0,NaN
7,37148747_397243,12:23:00,12:23:00,1474939,7,NaN,0,NaN
8,37148747_397243,12:28:00,12:28:00,1474938,8,NaN,0,NaN
9,37148747_397243,12:32:00,12:32:00,1474978,9,NaN,0,NaN
10,37148747_397243,12:39:00,12:39:00,1474931,10,NaN,0,NaN
11,37148747_397243,12:45:00,12:45:00,1474930,11,NaN,0,NaN
12,37148747_397243,12:50:00,12:51:00,1474929,12,NaN,0,NaN
13,37148747_397243,12:55:00,12:56:00,1474928,13,NaN,0,NaN
14,37148747_397243,13:02:00,13:02:00,1475236,14,NaN,0,NaN
15,37148747_397243,13:12:00,13:12:00,1474926,15,NaN,0,NaN
16,37148747_397243,13:15:00,13:15:00,1474925,16,NaN,1,NaN

In [13]:
stop_df = load_stop_data()
stop_df.head()

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,location_type,parent_station,platform_code
0,1413064,9429.0,Arnsdorf (b Dresden),NaN,51.093017,13.981679,1,NaN,NaN
1,1474632,NaN,Arnsdorf (b Dresden),NaN,51.093017,13.981679,0,1413064.0,NaN
2,1413065,6021.0,Bardo Przyłęk,NaN,50.509532,16.758018,1,NaN,NaN
3,1475207,NaN,Bardo Przyłęk,NaN,50.509532,16.758018,0,1413065.0,II
4,1474849,NaN,Bardo Przyłęk,NaN,50.509532,16.758018,0,1413065.0,I

In [14]:
parent_station_map = build_parent_station_map(stop_df)
print(str(parent_station_map[1474738]))
parent_station_map

1413380

{1474632: 1413064,
 1475207: 1413065,
 1474849: 1413065,
 1474644: 1413066,
 1474848: 1413066,
 1474813: 1413067,
 1474765: 1413067,
 1474942: 1413068,
 1474626: 1413069,
 1474828: 1413072,
 1475063: 1413073,
 1474840: 1413073,
 1703011: 1413074,
 1474853: 1413074,
 1474654: 1413075,
 1474698: 1413075,
 1474686: 1413076,
 1474687: 1413077,
 1474773: 1413078,
 2333183: 2246783,
 2414690: 2246783,
 2333187: 2246783,
 1474629: 1413079,
 2333191: 2246785,
 1474831: 1413080,
 1474759: 1413081,
 1474820: 1413081,
 1475153: 1413083,
 1474916: 1413083,
 1474917: 1413084,
 1475152: 1413084,
 2414693: 1413085,
 1475246: 1413085,
 1474690: 1413086,
 1474696: 1413086,
 1474945: 1413087,
 1475112: 1413087,
 1474855: 1413088,
 1475195: 1413088,
 1475211: 1413089,
 1475086: 1413089,
 1609774: 1413089,
 1874619: 1807626,
 1874618: 1807627,
 1474623: 1413090,
 1474982: 1413091,
 1474712: 1413091,
 2333170: 2246799,
 1536298: 1413092,
 1474786: 1413092,
 1475079: 1413093,
 1475242: 1413093,
 1536308: 1413093,
 1536295: 1413094,
 1475067: 1413094,
 1474789: 1413094,
 1536317: 1413095,
 1475098: 1413095,
 1474797: 1413096,
 1474798: 1413097,
 1474880: 1413098,
 1474879: 1413099,
 1474884: 1413099,
 1475057: 1413100,
 1475186: 1413101,
 1475074: 1413101,
 1536304: 1413101,
 1763296: 1413102,
 1474842: 1413102,
 1475062: 1413103,
 1474839: 1413103,
 1474946: 1413103,
 1475016: 1413104,
 1474959: 1413104,
 1475176: 1413105,
 1474919: 1413106,
 1475155: 1413106,
 1474981: 1413108,
 1609776: 1413107,
 1475095: 1413107,
 1475241: 1413110,
 1536309: 1413110,
 1475080: 1413110,
 1474788: 1413111,
 1475068: 1413111,
 1536296: 1413111,
 1474906: 1413112,
 1474628: 1413113,
 1474606: 1413114,
 1474609: 1413115,
 1474607: 1413116,
 1475085: 1413117,
 1475212: 1413117,
 1475224: 1413117,
 1474878: 1413118,
 1475089: 1413119,
 1475216: 1413119,
 1475225: 1413119,
 1475178: 1413120,
 1475173: 1413120,
 1474608: 1413121,
 1474662: 1413122,
 1474887: 1413123,
 1474877: 1413123,
 1474639: 1413124,
 1474636: 1413125,
 1474635: 1413127,
 1474638: 1413126,
 1474637: 1413128,
 1474649: 1413129,
 1609730: 1413129,
 1874612: 1413129,
 1474685: 1413130,
 1475231: 1413130,
 1475038: 1413131,
 1475198: 1413132,
 1474872: 1413132,
 1609760: 1413132,
 1474619: 1413133,
 1475138: 1413134,
 1475139: 1413135,
 1536315: 1413135,
 1474951: 1413136,
 1475008: 1413136,
 1475056: 1413136,
 1475082: 1413136,
 1475077: 1413137,
 1475244: 1413137,
 1536306: 1413137,
 1475243: 1413138,
 1536307: 1413138,
 1475078: 1413138,
 1474815: 1413139,
 1474763: 1413139,
 1474764: 1413140,
 1474814: 1413140,
 1474717: 1413141,
 1475245: 1413147,
 1474617: 1413142,
 1474618: 1413143,
 1657891: 1413144,
 1474881: 1413144,
 1474960: 1413145,
 1475017: 1413145,
 1474772: 1413146,
 1475156: 1413148,
 1475090: 1413149,
 1475226: 1413149,
 1475215: 1413149,
 1475009: 1413150,
 1474952: 1413150,
 1474968: 1413150,
 1474631: 1413151,
 1474978: 1413152,
 1474932: 1413152,
 1474611: 1413153,
 1474860: 1413154,
 1474852: 1413154,
 1475163: 1413155,
 1475148: 1413155,
 1609749: 1413156,
 1475191: 1413156,
 1474859: 1413156,
 1474598: 1413161,
 1474594: 1413157,
 1474595: 1413158,
 1474593: 1413159,
 1474596: 1413160,
 1474756: 1413162,
 1474822: 1413162,
 1474999: 1413163,
 1536322: 1413163,
 1475000: 1413163,
 1474715: 1413164,
 1475023: 1413164,
 1474720: 1413165,
 1474714: 1413165,
 1474691: 1413165,
 1474817: 1413166,
 1474762: 1413166,
 1474761: 1413167,
 1474802: 1413168,
 1474985: 1413180,
 1475187: 1413180,
 1609794: 1413180,
 1475177: 1413170,
 1474908: 1413170,
 1474907: 1413169,
 1536280: 1413171,
 1474925: 1413171,
 1474823: 1413171,
 1474755: 1413171,
 1475162: 1413171,
 2414698: 1413172,
 1475119: 1413172,
 1475158: 1413173,
 2414703: 1413173,
 2414704: 1413174,
 1475159: 1413174,
 1475165: 1413175,
 2414699: 1413175,
 1475120: 1413175,
 1474926: 1413176,
 1845554: 1413176,
 1475118: 1413176,
 2414705: 1413177,
 1475160: 1413177,
 1763303: 1413177,
 1764609: 1695529,
 1474944: 1413178,
 1475049: 1413179,
 1474846: 1413179,
 1474837: 1413179,
 1474801: 1413181,
 2333193: 2246891,
 2414694: 2246891,
 1474850: 1413182,
 1609796: 1413182,
 1475233: 1413182,
 1474643: 1413182,
 1474832: 1413183,
 2139845: 2040930,
 1474818: 1413184,
 1474795: 1413184,
 1474810: 1413185,
 1474991: 1413185,
 1474645: 1413185,
 1474749: 1413186,
 1474747: 1413187,
 1474774: 1413187,
 1474646: 1413187,
 1474750: 1413188,
 1474663: 1413189,
 2333189: 2246901,
 2414691: 2246901,
 1474610: 1413190,
 1474615: 1413191,
 1474873: 1413192,
 1609761: 1413192,
 1475197: 1413192,
 1474966: 1413193,
 1474956: 1413193,
 1475013: 1413193,
 1474829: 1413194,
 1474827: 1413195,
 1475092: 1413197,
 1475227: 1413197,
 1474746: 1413196,
 1474882: 1413196,
 1475097: 1413198,
 2114833: 1413198,
 1475076: 1413199,
 1536305: 1413199,
 1474695: 1413200,
 1536297: 1413201,
 1474787: 1413201,
 1475069: 1413201,
 1474625: 1413202,
 1474650: 1413203,
 1609731: 1413203,
 1474753: 1413204,
 2114836: 2040952,
 2114837: 2040952,
 2114835: 2040952,
 1474929: 1413205,
 1474740: 1413208,
 1474741: 1413209,
 1474634: 1413206,
 1874611: 1413207,
 1475188: 1413207,
 1475189: 1413207,
 1474847: 1413228,
 1475208: 1413228,
 1657886: 1413210,
 1474947: 1413210,
 1474836: 1413210,
 1609726: 1413210,
 1474843: 1413210,
 1609769: 1413211,
 1474909: 1413211,
 1609770: 1413212,
 1474910: 1413212,
 2414696: 2246926,
 2333192: 2246926,
 1475239: 1413213,
 1475029: 1413213,
 1474754: 1413214,
 1609747: 1413214,
 1474826: 1413215,
 1474588: 1413216,
 1474589: 1413217,
 1474888: 1413218,
 1475034: 1413219,
 2333169: 2246934,
 2333175: 2246934,
 2333178: 2246935,
 2333166: 2246935,
 1474622: 1413220,
 2114840: 2040977,
 2114839: 2040978,
 2114838: 2040979,
 1474785: 1413229,
 1475070: 1413229,
 1536299: 1413229,
 1474799: 1413221,
 1474940: 1413222,
 1474979: 1413222,
 1474980: 1413222,
 1474830: 1413223,
 1474958: 1413224,
 1474948: 1413224,
 1475015: 1413224,
 1475014: 1413225,
 1474957: 1413225,
 2414719: 2327643,
 1474599: 1413226,
 1474767: 1413227,
 1474997: 1413230,
 1475002: 1413230,
 1475030: 1413231,
 1475055: 1413231,
 1475072: 1413232,
 1475184: 1413232,
 1536302: 1413232,
 1474670: 1413233,
 1474757: 1413234,
 1474875: 1413238,
 1609762: 1413238,
 1474889: 1413238,
 1609777: 1413239,
 1474995: 1413240,
 1475004: 1413240,
 1475146: 1413237,
 1475144: 1413237,
 1475094: 1413242,
 1475228: 1413242,
 1657889: 1413242,
 2139848: 2040995,
 1474838: 1413243,
 1475050: 1413243,
 1474845: 1413243,
 1475026: 1413243,
 1475240: 1413243,
 2333190: 2246961,
 2414692: 2246961,
 1475084: 1413244,
 1475213: 1413244,
 1609773: 1413244,
 1474934: 1413245,
 1474931: 1413246,
 1475052: 1413247,
 1475027: 1413247,
 1474901: 1413248,
 1474893: 1413248,
 1475025: 1413249,
 1474684: 1413249,
 1474935: 1413250,
 1475005: 1413251,
 1474994: 1413251,
 2139846: 2041004,
 2139847: 2041005,
 1475174: 1413252,
 1475175: 1413253,
 2333181: 2246974,
 1536321: 1473564,
 1536289: 1473564,
 1474597: 1413254,
 1474811: 1413255,
 1474770: 1413255,
 1474769: 1413256,
 1474768: 1413257,
 1475081: 1413258,
 1475058: 1413258,
 1609756: 1413259,
 1474868: 1413259,
 1609791: 1413260,
 1475142: 1413260,
 1475129: 1413260,
 2333176: 2246986,
 2333168: 2246986,
 2333177: 2246987,
 2333167: 2246987,
 1474744: 1413264,
 1475210: 1413261,
 1475087: 1413261,
 1536316: 1413261,
 1475020: 1413261,
 1475022: 1413262,
 1475099: 1413262,
 1475088: 1413262,
 1474939: 1413263,
 1474936: 1413265,
 1536301: 1413266,
 1475071: 1413266,
 1475185: 1413266,
 1609792: 1413267,
 1475143: 1413267,
 1475128: 1413267,
 1609757: 1413268,
 1474869: 1413268,
 1475201: 1413268,
 1474734: 1413270,
 1474709: 1413270,
 1474867: 1413271,
 1475202: 1413271,
 1609755: 1413271,
 1475121: 1413272,
 1536314: 1413272,
 1475161: 1413272,
 2414702: 1413273,
 1475157: 1413273,
 1475135: 1413274,
 1609795: 1413274,
 1474984: 1413274,
 1474711: 1413275,
 1474736: 1413275,
 1475230: 1413276,
 1474612: 1413277,
 1474752: 1413278,
 1609728: 1413278,
 1474647: 1413278,
 2414720: 2327704,
 1474624: 1413279,
 1474975: 1413280,
 1474592: 1413281,
 1474933: 1413282,
 1475003: 1413283,
 1474996: 1413283,
 1474911: 1413284,
 1475024: 1413284,
 1474671: 1413285,
 1474665: 1413286,
 1474633: 1413287,
 1474742: 1413288,
 1474708: 1413289,
 1474733: 1413289,
 1475018: 1413290,
 1474961: 1413290,
 1474874: 1413291,
 1474891: 1413291,
 1475249: 1413291,
 1474930: 1413293,
 2414689: 1413293,
 1474620: 1413292,
 2114828: 1413295,
 1845555: 1413294,
 1474841: 1413296,
 1475039: 1413296,
 1475051: 1413296,
 1474876: 1413297,
 1474953: 1413298,
 1475010: 1413298,
 1474967: 1413298,
 1474954: 1413299,
 1475011: 1413299,
 1475075: 1413299,
 1475236: 1413300,
 1474927: 1413300,
 2414695: 2247024,
 2333194: 2247024,
 1475012: 1413301,
 1474955: 1413301,
 1475019: 1413302,
 1474962: 1413302,
 1474899: 1413303,
 1474895: 1413303,
 1475183: 1413339,
 1475073: 1413339,
 1536303: 1413339,
 1474771: 1413340,
 1474758: 1413305,
 1474821: 1413305,
 1474627: 1413304,
 1474904: 1413306,
 1474735: 1413307,
 1474710: 1413307,
 1475033: 1413308,
 1474870: 1413309,
 1609758: 1413309,
 1475200: 1413309,
 1474858: 1413310,
 1609748: 1413310,
 1475192: 1413310,
 1474900: 1413311,
 1474894: 1413311,
 1474600: 1413312,
 1474603: 1413313,
 1474601: 1413315,
 1474602: 1413314,
 1474667: 1413316,
 1474668: 1413317,
 2333184: 2247042,
 2333185: 2247042,
 2333186: 2247042,
 1475048: 1413341,
 1474949: 1413341,
 1474965: 1413341,
 1474719: 1413318,
 1475237: 1413319,
 1474928: 1413319,
 1474851: 1413320,
 1474883: 1413320,
 1474912: 1413321,
 1474751: 1413322,
 1474976: 1413323,
 1474739: 1413324,
 1474718: 1413325,
 1764608: 1695678,
 1474641: 1413326,
 1474886: 1413326,
 2414688: 2247053,
 1536285: 1413327,
 1475054: 1413327,
 1475209: 1413328,
 1474885: 1413328,
 1474688: 1413342,
 1474673: 1413342,
 1474672: 1413343,
 1474689: 1413344,
 1474697: 1413344,
 1475126: 1413345,
 1474989: 1413345,
 1474937: 1413346,
 1474766: 1413347,
 1474812: 1413347,
 2333180: 2247075,
 2333164: 2247075,
 1475104: 1413348,
 1474977: 1413329,
 1536313: 1413330,
 1475001: 1413331,
 1536323: 1413331,
 1474998: 1413331,
 1474669: 1413332,
 1609729: 1413333,
 1474648: 1413333,
 1609754: 1413334,
 1474866: 1413334,
 1475203: 1413334,
 1475122: 1413335,
 2414700: 1413335,
 1536272: 1413336,
 1474614: 1413336,
 1475127: 1413336,
 1475124: 1413336,
 1474613: 1413337,
 2414701: 1413338,
 1475123: 1413338,
 1474605: 1413349,
 1474604: 1413350,
 1609790: 1413351,
 1475130: 1413351,
 1475141: 1413351,
 1474824: 1413352,
 1474825: 1413353,
 1474920: 1413354,
 1609772: 1413354,
 1474743: 1413355,
 1474713: 1413356,
 1474737: 1413356,
 1475036: 1413357,
 1475035: 1413358,
 1474938: 1413359,
 1474590: 1413361,
 1474591: 1413362,
 1474780: 1413363,
 1474816: 1413363,
 1475147: 1413364,
 1475164: 1413364,
 1474781: 1413365,
 1474777: 1413365,
 1474760: 1413365,
 1474779: 1413366,
 1474990: 1413367,
 1475125: 1413367,
 1475196: 1413368,
 1474854: 1413368,
 1474988: 1413371,
 1475113: 1413371,
 1475190: 1413371,
 1475136: 1413371,
 1474983: 1413371,
 1475194: 1413372,
 1474856: 1413372,
 1474630: 1413369,
 1474664: 1413373,
 1475028: 1413374,
 1475053: 1413374,
 1609775: 1413375,
 1475093: 1413375,
 2333182: 2247103,
 2333188: 2247103,
 1475151: 1413376,
 1474918: 1413376,
 1475154: 1413377,
 1474921: 1413377,
 1536300: 1413378,
 1474784: 1413378,
 1474903: 1413379,
 1474861: 1413380,
 1474640: 1413380,
 1474738: 1413380,
 1536277: 1413380,
 1474679: 1413380,
 1536279: 1413380,
 1474651: 1413380,
 1474819: 1413381,
 1474794: 1413381,
 1475167: 1413382,
 1609787: 1413382,
 1474792: 1413383,
 1536292: 1413383,
 1475006: 1413384,
 1474993: 1413384,
 1474701: 1413385,
 1475181: 1413385,
 1474726: 1413385,
 1475046: 1413386,
 1474963: 1413386,
 1474793: 1413386,
 1474703: 1413387,
 1474728: 1413387,
 1474950: 1413388,
 1474964: 1413388,
 1475047: 1413388,
 1609752: 1413389,
 1475205: 1413389,
 1474864: 1413389,
 1474653: 1413390,
 1474699: 1413390,
 1474732: 1413391,
 1474707: 1413391,
 1609786: 1413392,
 1475168: 1413392,
 1474862: 1413393,
 1609750: 1413393,
 1536294: 1413394,
 1475066: 1413394,
 1474790: 1413394,
 1475083: 1413395,
 1474730: 1413395,
 1474705: 1413395,
 1609751: 1413396,
 1475206: 1413396,
 1474863: 1413396,
 1474704: 1413397,
 1474729: 1413397,
 1475214: 1413397,
 1475166: 1413397,
 1536293: 1413398,
 1474791: 1413398,
 1475065: 1413398,
 1475170: 1413399,
 1474865: 1413402,
 1475204: 1413402,
 1609753: 1413402,
 1609785: 1413400,
 1475179: 1413400,
 1474702: 1413401,
 1474727: 1413401,
 1475180: 1413401,
 1475171: 1413403,
 1475172: 1413404,
 1474700: 1413405,
 1474652: 1413405,
 1474892: 1413406,
 1474902: 1413406,
 1474706: 1413407,
 1474731: 1413407,
 1474992: 1413408,
 1475007: 1413408,
 1475229: 1413414,
 1475232: 1413414,
 1874617: 1807949,
 1475140: 1413409,
 1475132: 1413409,
 1609788: 1413409,
 1763298: 1413422,
 1475031: 1413422,
 1474800: 1413410,
 1474905: 1413411,
 1474941: 1413412,
 1474796: 1413423,
 1475061: 1413424,
 1475064: 1413424,
 1475032: 1413424,
 1475238: 1413424,
 1475037: 1413413,
 2414697: 1413415,
 1475096: 1413415,
 2333179: 2247146,
 2333165: 2247146,
 1609789: 1413416,
 1475131: 1413416,
 1475137: 1413416,
 1474745: 1413425,
 1609725: 1413417,
 1474987: 1413417,
 1474616: 1413417,
 1475133: 1413417,
 1609793: 1413418,
 1474986: 1413418,
 1475134: 1413418,
 1474890: 1413420,
 1474642: 1413420,
 1845557: 1413419,
 1536288: 1413419,
 1536287: 1413419,
 1536290: 1473734,
 1536320: 1473734,
 1536319: 1473735,
 1536291: 1473735,
 1609759: 1413426,
 1475199: 1413426,
 1474871: 1413426,
 1474621: 1413421,
 1475193: 1413427,
 1474857: 1413427}

In [15]:
graph = get_graph(trips_dict, parent_station_map)
print(graph.keys())
graph[1413417][:5]
# 1609725

dict_keys([1413194, 1413223, 1413080, 1413183, 1413305, 1413153, 1413277, 1413337, 1413336, 1413142, 1413417, 1413178, 2247053, 1413068, 1413412, 1413222, 1413263, 1413359, 1413152, 1413246, 1413293, 1413205, 1413319, 1413300, 1413176, 1413171, 1413282, 1413245, 1413250, 1413265, 1413346, 2040979, 2040978, 2040977, 2041004, 2041005, 2040995, 2040930, 1413418, 1413180, 1413207, 1413274, 1413371, 1413380, 1413386, 1413092, 1413378, 1413339, 1413299, 1413150, 1413136, 1413326, 1413420, 1413182, 1413066, 1413185, 1413187, 1413278, 1413333, 1413129, 1413203, 1413405, 1413390, 1413075, 1413122, 1413189, 1413373, 1413286, 1413295, 1413316, 1413317, 1695678, 1413332, 1413233, 1413285, 1413343, 1413342, 1413130, 1413076, 1413077, 1413200, 1413249, 1413165, 1413086, 1413344, 1413385, 1413401, 1413387, 1413397, 1413395, 1413407, 1413391, 1413289, 1413270, 1413307, 1413091, 1413356, 1413164, 1413294, 1413141, 1413325, 1413318, 1413379, 2247075, 2247146, 2246935, 2246987, 2246986, 2246934, 2246799, 1413381, 1413406, 1413248, 1413311, 1413303, 1413184, 1413237, 1413155, 1413423, 1413345, 1413367, 1413366, 1413363, 1413364, 1413365, 1413083, 1413081, 1413084, 1413376, 1413234, 1413106, 1413162, 1413354, 1413377, 1413186, 1413188, 1413322, 1413214, 1413167, 1413166, 1413139, 1413140, 1413067, 1413347, 1413227, 1413257, 1413256, 1413255, 1413340, 1413146, 1413078, 1413210, 1413179, 1413243, 1413103, 1413073, 1413296, 1413102, 1413228, 1413065, 1413320, 1413154, 1413074, 1413368, 1413088, 1413372, 1413427, 1413310, 1413156, 1413393, 1413396, 1413389, 1413402, 1413334, 1413271, 1413259, 1413268, 1413309, 1413426, 1413132, 1413192, 1413291, 1413238, 1413297, 1413123, 1413118, 1413099, 1413098, 1413144, 1413196, 1413328, 2246974, 2247103, 2246783, 2247042, 1413261, 1413089, 1413117, 1413244, 1413218, 1413224, 1413341, 1413388, 1413298, 1413301, 1413193, 1413225, 1413104, 1413145, 1413290, 1413302, 1413416, 1413087, 1413275, 1413408, 1413384, 1413251, 1413240, 1413283, 1413230, 1413331, 1413163, 2040952, 1413108, 1413135, 1413134, 1413211, 1413212, 1413284, 1413321, 1413096, 1413097, 1413221, 1413410, 1413181, 1413168, 1413247, 1413374, 1413213, 1413231, 1413422, 1413424, 1413308, 1413219, 1413358, 1413357, 1413100, 1413258, 1413419, 1413327, 1413137, 1413138, 1413093, 1413110, 1473564, 1473734, 1473735, 1413383, 1413398, 1413394, 1413094, 1413111, 1413201, 1413229, 1413266, 1413232, 1413101, 1413199, 1413170, 1413169, 1413112, 1413411, 1413306, 1413262, 1413119, 1413149, 1413095, 1413197, 1413375, 1413242, 1413107, 1413415, 1413198, 1413172, 1413175, 1413272, 1413335, 1413338, 1413267, 1413260, 1413351, 1413409, 1413148, 1413273, 1413173, 1413174, 1413177, 1413382, 1413392, 1413400, 1413399, 1413403, 1413404, 1413120, 1413252, 1413253, 1413105, 2246901, 2246961, 2246785, 1413276, 1413414, 1413085])

[{'to': 1413178,
  'dep_time': 20640,
  'arr_time': 21000,
  'time': 360,
  'trip_id': '37148619_397115'},
 {'to': 1413178,
  'dep_time': 27840,
  'arr_time': 28200,
  'time': 360,
  'trip_id': '37148622_397118'},
 {'to': 1413178,
  'dep_time': 35040,
  'arr_time': 35400,
  'time': 360,
  'trip_id': '37148625_397121'},
 {'to': 1413178,
  'dep_time': 49440,
  'arr_time': 49800,
  'time': 360,
  'trip_id': '37148628_397124'},
 {'to': 1413178,
  'dep_time': 56640,
  'arr_time': 57000,
  'time': 360,
  'trip_id': '37148631_397127'}]

In [16]:
graph_with_names = add_stop_names_to_graph(graph, stop_df)
graph_with_names[1413417][:5]

[{'to': 1413178,
  'dep_time': 20640,
  'arr_time': 21000,
  'time': 360,
  'trip_id': '37148619_397115',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki'},
 {'to': 1413178,
  'dep_time': 27840,
  'arr_time': 28200,
  'time': 360,
  'trip_id': '37148622_397118',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki'},
 {'to': 1413178,
  'dep_time': 35040,
  'arr_time': 35400,
  'time': 360,
  'trip_id': '37148625_397121',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki'},
 {'to': 1413178,
  'dep_time': 49440,
  'arr_time': 49800,
  'time': 360,
  'trip_id': '37148628_397124',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki'},
 {'to': 1413178,
  'dep_time': 56640,
  'arr_time': 57000,
  'time': 360,
  'trip_id': '37148631_397127',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki'}]

In [17]:
routes_df = load_routes_data()
routes_df.head()

,route_id,agency_id,route_short_name,route_long_name,route_type,route_color,route_text_color
0,234113,279,D1,NaN,2,F6C32F,0
1,234091,279,D10,NaN,2,F6C32F,0
2,234097,279,D11,NaN,2,F6C32F,0
3,234126,279,D12,NaN,2,F6C32F,0
4,234107,279,D13,NaN,2,F6C32F,0

In [18]:
lines_map = build_line_ids_map(filtered_trips_df, routes_df)
lines_map['37148499_396995']

'D66'

In [19]:
add_line_names_to_graph(graph_with_names, lines_map)

In [20]:
final_graph = sort_graph_by_stop_dep(graph_with_names)
[edge for edge in final_graph[1413417] if edge['to_stop_name'] == "Jerzmanki"]

[{'to': 1413178,
  'dep_time': 20640,
  'arr_time': 21000,
  'time': 360,
  'trip_id': '37148619_397115',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'},
 {'to': 1413178,
  'dep_time': 27840,
  'arr_time': 28200,
  'time': 360,
  'trip_id': '37148622_397118',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'},
 {'to': 1413178,
  'dep_time': 35040,
  'arr_time': 35400,
  'time': 360,
  'trip_id': '37148625_397121',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'},
 {'to': 1413178,
  'dep_time': 42240,
  'arr_time': 42600,
  'time': 360,
  'trip_id': '37148747_397243',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'},
 {'to': 1413178,
  'dep_time': 49440,
  'arr_time': 49800,
  'time': 360,
  'trip_id': '37148628_397124',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'},
 {'to': 1413178,
  'dep_time': 56640,
  'arr_time': 57000,
  'time': 360,
  'trip_id': '37148631_397127',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'},
 {'to': 1413178,
  'dep_time': 63840,
  'arr_time': 64200,
  'time': 360,
  'trip_id': '37148634_397130',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'},
 {'to': 1413178,
  'dep_time': 71040,
  'arr_time': 71400,
  'time': 360,
  'trip_id': '37148637_397133',
  'from_stop_name': 'Zgorzelec',
  'to_stop_name': 'Jerzmanki',
  'line_name': 'D62'}]

In [21]:
graph_test = get_graph_for_date(test_date, with_locations=True)
len([edge for edge in graph_test[1413417] if edge['to_stop_name'] == "Görlitz"])

19

In [22]:
graph = Graph(test_date, with_locations=True)
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

graph.load_next_day()
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

graph.load_next_day()
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

graph.load_next_day()
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

19
38
57
76

In [23]:
edge_date = pd.Timestamp("2026-12-11")

graph = Graph(edge_date, with_locations=True)
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

graph.load_next_day()
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

graph.load_next_day()
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

graph.load_next_day()
print(str(len([edge for edge in graph.graph[1413417] if edge['to_stop_name'] == "Görlitz"])))

19
37
37
37